# Generated by Django 3.1.4 on 2021-02-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0002_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rating',
        ),
        migrations.AddField(
            model_name='student',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
